import { SERVICE_TYPE } from "@/common/constants/domain";
import type { ReceivedRequestViewModel } from "./mover-requests.types";

export const MOCK_RECEIVED_REQUESTS: ReceivedRequestViewModel[] = [
  {
    requestId: "request-1",
    customerName: "김인서",
    serviceType: SERVICE_TYPE.SMALL,
    isDesignated: true,
    requestedAt: "2024-06-30T09:00:00+09:00",
    requestedAtLabel: "1시간 전",
    departureLabel: "서울시 중구",
    arrivalLabel: "경기도 수원시",
    moveDate: "2024-07-01",
    moveDateLabel: "2024년 07월 01일 (월)",
  },
  {
    requestId: "request-2",
    customerName: "박무빙",
    serviceType: SERVICE_TYPE.HOME,
    isDesignated: true,
    requestedAt: "2024-06-30T08:00:00+09:00",
    requestedAtLabel: "2시간 전",
    departureLabel: "서울시 마포구",
    arrivalLabel: "인천시 연수구",
    moveDate: "2024-07-08",
    moveDateLabel: "2024년 07월 08일 (월)",
  },
  {
    requestId: "request-3",
    customerName: "이코드",
    serviceType: SERVICE_TYPE.OFFICE,
    isDesignated: false,
    requestedAt: "2024-06-29T15:00:00+09:00",
    requestedAtLabel: "1일 전",
    departureLabel: "서울시 강남구",
    arrivalLabel: "경기도 성남시",
    moveDate: "2024-07-15",
    moveDateLabel: "2024년 07월 15일 (월)",
  },
  {
    requestId: "request-4",
    customerName: "최이사",
    serviceType: SERVICE_TYPE.SMALL,
    isDesignated: false,
    requestedAt: "2024-06-29T12:00:00+09:00",
    requestedAtLabel: "1일 전",
    departureLabel: "서울시 종로구",
    arrivalLabel: "경기도 고양시",
    moveDate: "2024-07-20",
    moveDateLabel: "2024년 07월 20일 (토)",
  },
];
